// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Footer() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"sticky bottom-0 py-4 bg-white\"><div class=\"flex gap-3\"><p class=\"text-sm\">Built with:</p><a class=\"text-cyan-600 text-xs\" href=\"https://go.dev/\" target=\"_blank\">golang</a> <a class=\"text-cyan-600 text-xs\" href=\"https://htmx.org/\" target=\"_blank\">htmx</a> <a class=\"text-cyan-600 text-xs\" href=\"https://templ.guide/\" target=\"_blank\">templ</a> <a class=\"text-cyan-600 text-xs\" href=\"https://tailwindcss.com/\" target=\"_blank\">tailwindcss</a></div><a class=\"text-cyan-600 text-xs\" href=\"https://github.com/atos-digital/10100-template\" target=\"_blank\">Source code</a></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
